# Generated by Django 5.2.8 on 2026-09-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
        ('customers', '0003_initial'),
        ('procurement_pos', '0002_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='posregister',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='posregister',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_registers', to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='possession',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='procurement_pos.posregister'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='procurement_pos.possession'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_pos.postransaction'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='goods_received_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement_pos.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Purchase Order billing currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement_pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='procurement_pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='procurement_pos.purchaserequest'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Sales Invoice transaction currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_tax_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.salestaxtemplate'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_items', to='shop.product'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='sales_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_pos.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_items', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Contact person line associated with this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='customers.customercontact'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Sales Order transaction currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Delivery address line for order fulfillment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='customers.customeraddress'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='procurement_pos.salesorder'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='procurement_pos.salesorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement_pos.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement_pos.supplier'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotations', to='procurement_pos.requestforquotation'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement_pos.supplier'),
        ),
    ]
