# Generated by Django 5.2.8 on 2026-09-06 05:50

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_pos', '0003_initial'),
        ('shop', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteLine',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='grnl_', primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement_pos.goodsreceivednote')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_lines', to='procurement_pos.purchaseorderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='shop.productvariant')),
            ],
            options={
                'verbose_name': 'GRN Line',
                'verbose_name_plural': 'GRN Lines',
                'db_table': 'procurement_grn_lines',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrderEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='poev_', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], help_text='PO status recorded by this event', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_tracking_events', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='procurement_pos.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Tracking Event',
                'verbose_name_plural': 'Purchase Order Tracking Events',
                'db_table': 'procurement_po_tracking_events',
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineTracking',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='polt_', primary_key=True, serialize=False)),
                ('carrier_name', core.base_models.fields.char_fields.CustomCharField(help_text='Courier / carrier e.g. FedEx, DHL', max_length=150)),
                ('tracking_number', core.base_models.fields.char_fields.CustomCharField(help_text='Carrier tracking number / consignment reference', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Shipment'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed')], default='PENDING', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='procurement_pos.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Tracking',
                'verbose_name_plural': 'Purchase Order Line Trackings',
                'db_table': 'procurement_po_line_trackings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
