# Generated by Django 5.2.8 on 2026-09-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_pos', '0004_purchaseorderitem_status_goodsreceivednoteline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, help_text='Source requisition this PO fulfils', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement_pos.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_quotation',
            field=models.ForeignKey(blank=True, help_text='Selected vendor quotation this PO was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement_pos.vendorquotation'),
        ),
    ]
