# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import core.base_models.validators.email_validator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='cust_', primary_key=True, serialize=False)),
                ('customer_code', core.base_models.fields.char_fields.CustomCharField(blank=True, default='', help_text='Unique customer identifier code.', max_length=50)),
                ('name', core.base_models.fields.char_fields.CustomCharField(help_text='Customer display name or business entity name.', max_length=200)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual (B2C)'), ('CORPORATE', 'Corporate / Enterprise (B2B)')], default='INDIVIDUAL', max_length=30)),
                ('email', core.base_models.fields.char_fields.CustomEmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address with a proper domain.', regex='^[\\w\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$'), core.base_models.validators.email_validator.validate_email_domain])),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax / VAT / GST Registration ID', max_length=50, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='addr_', primary_key=True, serialize=False)),
                ('title', models.CharField(default='Home', help_text='Label e.g. Home, Office, Warehouse 1', max_length=100)),
                ('address_type', models.CharField(choices=[('DELIVERY', 'Delivery Address'), ('BILLING', 'Billing Address'), ('BOTH', 'Delivery & Billing')], default='DELIVERY', max_length=20)),
                ('attention_to', models.CharField(blank=True, help_text='Recipient name', max_length=150, null=True)),
                ('address_line_1', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', core.base_models.fields.char_fields.CustomCharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', core.base_models.fields.char_fields.CustomCharField(max_length=20)),
                ('country', core.base_models.fields.char_fields.CustomCharField(default='USA', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='Serviceability pincode', max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default_delivery', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Address Line',
                'verbose_name_plural': 'Customer Address Lines',
                'db_table': 'customer_address_lines',
                'ordering': ['-is_default_delivery', 'title'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='cnt_', primary_key=True, serialize=False)),
                ('contact_name', core.base_models.fields.char_fields.CustomCharField(max_length=150)),
                ('designation', models.CharField(blank=True, help_text='e.g. Procurement Officer, Manager', max_length=100, null=True)),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary Contact'), ('BILLING', 'Accounts / Billing Contact'), ('SHIPPING', 'Logistics / Shipping Contact'), ('TECHNICAL', 'Technical Contact')], default='PRIMARY', max_length=20)),
                ('email', core.base_models.fields.char_fields.CustomEmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address with a proper domain.', regex='^[\\w\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$'), core.base_models.validators.email_validator.validate_email_domain])),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Contact Line',
                'verbose_name_plural': 'Customer Contact Lines',
                'db_table': 'customer_contact_lines',
                'ordering': ['-is_primary', 'contact_name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartyLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('party_type', models.CharField(blank=True, db_index=True, help_text='Model name of the party entity (e.g. Customer, Supplier, UserProfileModel)', max_length=50, null=True)),
                ('party_id', models.CharField(blank=True, db_index=True, help_text='Primary key of the party entity', max_length=50, null=True)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='ple_', primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('PAYMENT_ENTRY', 'Payment Entry'), ('JOURNAL_ENTRY', 'Journal Entry')], default='SALES_INVOICE', max_length=50)),
                ('voucher_id', models.CharField(help_text='ID of source invoice or payment entry', max_length=50)),
                ('voucher_no', models.CharField(help_text='Human-readable code e.g. INV-2026-0001', max_length=100)),
                ('posting_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_reconciled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Party Ledger Entry',
                'verbose_name_plural': 'Party Ledger Entries',
                'db_table': 'party_ledger_entries',
                'ordering': ['posting_date', 'created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='like_', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Product Likes',
                'db_table': 'customer_product_likes',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='soc_', primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='OAuth Provider e.g. GOOGLE, GITHUB, FACEBOOK, APPLE, MICROSOFT', max_length=30)),
                ('uid', models.CharField(help_text='Provider unique user identifier', max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'customer_social_accounts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='wish_', primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Wishlist', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'db_table': 'customer_wishlists',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='witem_', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'db_table': 'customer_wishlist_items',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='cart_', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKOUT', 'In Checkout'), ('CONVERTED', 'Converted to Order'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.ForeignKey(blank=True, help_text='Cart checkout currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_carts', to='accounting.currency')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'customer_carts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='citem_', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_disabled', models.BooleanField(default=False, help_text='If true, item is moved to disabled cart section (out of stock, seller inactive, price changed)')),
                ('disable_reason', models.CharField(blank=True, help_text='Reason code e.g. OUT_OF_STOCK, SELLER_INACTIVE, PRODUCT_UNAVAILABLE, INSUFFICIENT_STOCK', max_length=50, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'customer_cart_items',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
