# Generated by Django 5.2.8 on 2026-09-04 11:49

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0004_company_default_currency_numberseries'),
        ('customers', '0001_initial'),
        ('shop', '0002_brand_remove_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default_delivery', 'title'], 'verbose_name': 'Customer Address Line', 'verbose_name_plural': 'Customer Address Lines'},
        ),
        migrations.AlterModelOptions(
            name='customercontact',
            options={'ordering': ['-is_primary', 'contact_name'], 'verbose_name': 'Customer Contact Line', 'verbose_name_plural': 'Customer Contact Lines'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='customerpreference',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Cart checkout currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_carts', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKOUT', 'In Checkout'), ('CONVERTED', 'Converted to Order'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='disable_reason',
            field=models.CharField(blank=True, help_text='Reason code e.g. OUT_OF_STOCK, SELLER_INACTIVE, PRODUCT_UNAVAILABLE, INSUFFICIENT_STOCK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='citem_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='If true, item is moved to disabled cart section (out of stock, seller inactive, price changed)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=core.base_models.fields.char_fields.CustomCharField(blank=True, default='', help_text='Unique customer identifier code.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual (B2C)'), ('CORPORATE', 'Corporate / Enterprise (B2B)')], default='INDIVIDUAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=core.base_models.fields.char_fields.CustomCharField(help_text='Customer display name or business entity name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax / VAT / GST Registration ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional link to authenticated portal user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line_1',
            field=core.base_models.fields.char_fields.CustomCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery Address'), ('BILLING', 'Billing Address'), ('BOTH', 'Delivery & Billing')], default='DELIVERY', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='attention_to',
            field=models.CharField(blank=True, help_text='Recipient name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=core.base_models.fields.char_fields.CustomCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=core.base_models.fields.char_fields.CustomCharField(default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='id',
            field=core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='addr_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(blank=True, help_text='Serviceability pincode', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=core.base_models.fields.char_fields.CustomCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(default='Home', help_text='Label e.g. Home, Office, Warehouse 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='contact_name',
            field=core.base_models.fields.char_fields.CustomCharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='contact_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary Contact'), ('BILLING', 'Accounts / Billing Contact'), ('SHIPPING', 'Logistics / Shipping Contact'), ('TECHNICAL', 'Technical Contact')], default='PRIMARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g. Procurement Officer, Manager', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='cnt_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text='Customer preferred storefront display currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_preferences', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='id',
            field=core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='like_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(help_text='OAuth Provider e.g. GOOGLE, GITHUB, FACEBOOK, APPLE, MICROSOFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='uid',
            field=models.CharField(help_text='Provider unique user identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='My Wishlist', max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='witem_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='shop.productvariant'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='customer_carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='customer_cart_items',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='customeraddress',
            table='customer_address_lines',
        ),
        migrations.AlterModelTable(
            name='customercontact',
            table='customer_contact_lines',
        ),
        migrations.AlterModelTable(
            name='customerpreference',
            table='customer_preferences',
        ),
        migrations.AlterModelTable(
            name='productlike',
            table='customer_product_likes',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='customer_wishlists',
        ),
        migrations.AlterModelTable(
            name='wishlistitem',
            table='customer_wishlist_items',
        ),
        migrations.CreateModel(
            name='PartyLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('party_type', models.CharField(blank=True, db_index=True, help_text='Model name of the party entity (e.g. Customer, Supplier, UserProfileModel)', max_length=50, null=True)),
                ('party_id', models.CharField(blank=True, db_index=True, help_text='Primary key of the party entity', max_length=50, null=True)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='ple_', primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('PAYMENT_ENTRY', 'Payment Entry'), ('JOURNAL_ENTRY', 'Journal Entry')], default='SALES_INVOICE', max_length=50)),
                ('voucher_id', models.CharField(help_text='ID of source invoice or payment entry', max_length=50)),
                ('voucher_no', models.CharField(help_text='Human-readable code e.g. INV-2026-0001', max_length=100)),
                ('posting_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_ledger_entries', to='core_admin.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_ledger_entries', to='core_admin.company')),
                ('party_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Party Ledger Entry',
                'verbose_name_plural': 'Party Ledger Entries',
                'db_table': 'party_ledger_entries',
                'ordering': ['posting_date', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'posting_date'], name='party_ledge_company_c723ee_idx'), models.Index(fields=['party_type', 'party_id'], name='party_ledge_party_t_8dbd7e_idx')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
