# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_admin', '0001_initial'),
        ('customers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shop.productvariant'),
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='customers.customer')),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('newsletter_opt_in', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('default_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Customer Preference',
                'verbose_name_plural': 'Customer Preferences',
                'db_table': 'customer_preferences',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company / tenant this customer belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core_admin.company'),
        ),
    ]
