# Generated by Django 5.2.8 on 2026-09-05 05:55

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0004_deliverypartner_facilitypolicyrule_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='kbc_', primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=120)),
                ('slug', core.base_models.fields.char_fields.CustomCharField(max_length=140)),
                ('description', core.base_models.fields.char_fields.CustomTextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledgebase.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'db_table': 'kb_categories',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='art_', primary_key=True, serialize=False)),
                ('title', core.base_models.fields.char_fields.CustomCharField(max_length=200)),
                ('slug', core.base_models.fields.char_fields.CustomCharField(max_length=220)),
                ('summary', core.base_models.fields.char_fields.CustomTextField(blank=True, null=True)),
                ('content', models.TextField(help_text='Markdown or rich text article body')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('is_internal_only', models.BooleanField(default=False, help_text='If true, restricted to staff/cashier/procurement roles')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledgebase.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'db_table': 'kb_articles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductKnowledgeLink',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='pkl_', primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Polymorphic target object primary key ID', max_length=50, null=True)),
                ('target_identifier', models.CharField(blank=True, db_index=True, help_text='Direct lookup identifier e.g. Product ID/Slug, Facility Code, Bin Code', max_length=150, null=True)),
                ('link_type', models.CharField(choices=[('USER_MANUAL', 'User Manual'), ('TROUBLESHOOTING', 'Troubleshooting Guide'), ('CASHIER_PITCH', 'POS Cashier Sales Pitch'), ('COMPLIANCE_CERT', 'Procurement Compliance Certificate'), ('ASSEMBLY_BOM', 'Assembly / BOM Diagram'), ('SPEC_SHEET', 'Technical Spec Sheet'), ('FACILITY_SOP', 'Facility Standard Operating Procedure (SOP)'), ('BIN_SAFETY_RULE', 'Storage Location & Bin Safety Rules'), ('HAZMAT_HANDLING', 'Hazardous Material Handling Guide')], default='SPEC_SHEET', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='knowledgebase.knowledgearticle')),
                ('content_type', models.ForeignKey(blank=True, help_text='Polymorphic target model e.g. Product, Facility, StorageLocation, FacilityInventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility SOPs, Operating Hours, Access Protocols', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.facility')),
                ('facility_inventory', models.ForeignKey(blank=True, help_text='Item-specific Handling Guides, Assembly Docs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.facilityinventory')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.inventory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.product')),
                ('shop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.category')),
                ('storage_location', models.ForeignKey(blank=True, help_text='Storage Bin Hazmat, Max Load Weight, Safety Rules', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.storagelocation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.productvariant')),
            ],
            options={
                'verbose_name': 'Product & Entity Knowledge Link',
                'verbose_name_plural': 'Product & Entity Knowledge Links',
                'db_table': 'kb_product_knowledge_links',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['target_identifier', 'link_type'], name='kb_product__target__92ea23_idx'), models.Index(fields=['content_type', 'object_id'], name='kb_product__content_e688f2_idx')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
