# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='art_', primary_key=True, serialize=False)),
                ('title', core.base_models.fields.char_fields.CustomCharField(max_length=200)),
                ('slug', core.base_models.fields.char_fields.CustomCharField(max_length=220)),
                ('summary', core.base_models.fields.char_fields.CustomTextField(blank=True, null=True)),
                ('content', models.TextField(help_text='Markdown or rich text article body')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('is_internal_only', models.BooleanField(default=False, help_text='If true, restricted to staff/cashier/procurement roles')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'db_table': 'kb_articles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='kbc_', primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=120)),
                ('slug', core.base_models.fields.char_fields.CustomCharField(max_length=140)),
                ('description', core.base_models.fields.char_fields.CustomTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'db_table': 'kb_categories',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductKnowledgeLink',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='pkl_', primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Polymorphic target object primary key ID', max_length=50, null=True)),
                ('target_identifier', models.CharField(blank=True, db_index=True, help_text='Direct lookup identifier e.g. Product ID/Slug, Facility Code, Bin Code', max_length=150, null=True)),
                ('link_type', models.CharField(choices=[('USER_MANUAL', 'User Manual'), ('TROUBLESHOOTING', 'Troubleshooting Guide'), ('CASHIER_PITCH', 'POS Cashier Sales Pitch'), ('COMPLIANCE_CERT', 'Procurement Compliance Certificate'), ('ASSEMBLY_BOM', 'Assembly / BOM Diagram'), ('SPEC_SHEET', 'Technical Spec Sheet'), ('FACILITY_SOP', 'Facility Standard Operating Procedure (SOP)'), ('BIN_SAFETY_RULE', 'Storage Location & Bin Safety Rules'), ('HAZMAT_HANDLING', 'Hazardous Material Handling Guide')], default='SPEC_SHEET', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Product & Entity Knowledge Link',
                'verbose_name_plural': 'Product & Entity Knowledge Links',
                'db_table': 'kb_product_knowledge_links',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
