# Generated by Django 5.2.8 on 2026-09-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledgebase', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledgebase.knowledgecategory'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledgebase.knowledgecategory'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='knowledgebase.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Polymorphic target model e.g. Product, Facility, StorageLocation, FacilityInventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility SOPs, Operating Hours, Access Protocols', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.facility'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='facility_inventory',
            field=models.ForeignKey(blank=True, help_text='Item-specific Handling Guides, Assembly Docs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.facilityinventory'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.inventory'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.category'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Storage Bin Hazmat, Max Load Weight, Safety Rules', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.storagelocation'),
        ),
        migrations.AddField(
            model_name='productknowledgelink',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='shop.productvariant'),
        ),
        migrations.AddIndex(
            model_name='productknowledgelink',
            index=models.Index(fields=['target_identifier', 'link_type'], name='kb_product__target__92ea23_idx'),
        ),
        migrations.AddIndex(
            model_name='productknowledgelink',
            index=models.Index(fields=['content_type', 'object_id'], name='kb_product__content_e688f2_idx'),
        ),
    ]
