# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='acc_', primary_key=True, serialize=False)),
                ('account_code', core.base_models.fields.char_fields.CustomCharField(help_text='Unique account code e.g. 1000-CASH, 1200-AR', max_length=50)),
                ('account_name', core.base_models.fields.char_fields.CustomCharField(help_text='Display name of the account', max_length=200)),
                ('root_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income / Revenue'), ('EXPENSE', 'Expense')], default='ASSET', max_length=30)),
                ('account_type', models.CharField(blank=True, choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account'), ('RECEIVABLE', 'Accounts Receivable (AR)'), ('PAYABLE', 'Accounts Payable (AP)'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold (COGS)'), ('STOCK_IN_HAND', 'Stock in Hand (Inventory)'), ('DIRECT_EXPENSE', 'Direct Expense'), ('INDIRECT_EXPENSE', 'Indirect Expense'), ('TAX', 'Tax / Duty Account'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation'), ('RETAINED_EARNINGS', 'Retained Earnings')], max_length=50, null=True)),
                ('currency', models.CharField(blank=True, help_text='Account posting currency; defaults to Company Base Currency if unassigned', max_length=5, null=True)),
                ('is_group', models.BooleanField(default=False, help_text='Group accounts hold sub-accounts and cannot receive direct GL postings')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'accounting_accounts',
                'ordering': ['account_code'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
