# Generated by Django 5.2.8 on 2026-09-06 04:27

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeDefinition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='chgd_', primary_key=True, serialize=False)),
                ('code', core.base_models.fields.char_fields.CustomCharField(help_text='Unique charge code per company e.g. FLAT_SHIPPING, HANDLING_5PCT', max_length=50)),
                ('title', core.base_models.fields.char_fields.CustomCharField(help_text='Human readable label e.g. Flat Rate Shipping, Holiday Discount 10%', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('charge_type', models.CharField(choices=[('ADDITIONAL', 'Additional / Surcharge (Adds To Total)'), ('DISCOUNT', 'Discount (Reduces Total)'), ('TAX_SURCHARGE', 'Tax Surcharge (Levied With Tax)')], default='ADDITIONAL', help_text='Whether the charge adds to or reduces the document total', max_length=30)),
                ('based_on', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage Of Document Total'), ('PER_UNIT', 'Fixed Amount Per Unit')], default='FIXED_AMOUNT', help_text='Basis used to compute the charge amount', max_length=30)),
                ('rate', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=3, default=0, help_text='Percentage rate for PERCENTAGE charges, or per-unit value for PER_UNIT charges', max_digits=8)),
                ('amount', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0, help_text='Fixed amount for FIXED_AMOUNT charges', max_digits=12)),
                ('scope', models.CharField(choices=[('ALL', 'All Documents'), ('SALES_ORDER', 'Sales Orders'), ('PURCHASE_ORDER', 'Purchase Orders'), ('SALES_INVOICE', 'Sales Invoices'), ('PURCHASE_INVOICE', 'Purchase Invoices'), ('POS', 'POS Transactions'), ('SHOP_ORDER', 'E-Commerce Shop Orders')], default='ALL', help_text='Documents this charge may be applied to', max_length=30)),
                ('is_inclusive', models.BooleanField(default=False, help_text='If true, the charge amount already includes its tax')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, help_text='GL account the charge amount posts to (e.g. Shipping Income, Service Charge)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_definitions', to='accounting.account')),
                ('company', models.ForeignKey(help_text='Company this charge definition belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='charge_definitions', to='core_admin.company')),
                ('item_tax_template', models.ForeignKey(blank=True, help_text='Item-level tax template fallback for charge tax computation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='accounting.itemtaxtemplate')),
                ('purchase_tax_template', models.ForeignKey(blank=True, help_text='Purchase tax template whose rates drive tax on this charge for purchase documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='accounting.purchasetaxtemplate')),
                ('sales_tax_template', models.ForeignKey(blank=True, help_text='Sales tax template whose rates drive tax on this charge for sales documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='accounting.salestaxtemplate')),
            ],
            options={
                'verbose_name': 'Charge Definition',
                'verbose_name_plural': 'Charge Definitions',
                'db_table': 'accounting_charge_definitions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='chg_', primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Polymorphic parent document primary key', max_length=50, null=True)),
                ('charge_type', models.CharField(choices=[('ADDITIONAL', 'Additional / Surcharge (Adds To Total)'), ('DISCOUNT', 'Discount (Reduces Total)'), ('TAX_SURCHARGE', 'Tax Surcharge (Levied With Tax)')], default='ADDITIONAL', max_length=30)),
                ('based_on', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage Of Document Total'), ('PER_UNIT', 'Fixed Amount Per Unit')], default='FIXED_AMOUNT', max_length=30)),
                ('rate', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=3, default=0, max_digits=8)),
                ('amount', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('content_type', models.ForeignKey(blank=True, help_text='Polymorphic parent document type (SalesOrder, PurchaseOrder, Invoice, POS, Shop Order)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='accounting.currency')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_items', to='accounting.chargedefinition')),
                ('item_tax_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='accounting.itemtaxtemplate')),
                ('purchase_tax_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='accounting.purchasetaxtemplate')),
                ('sales_tax_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='accounting.salestaxtemplate')),
            ],
            options={
                'verbose_name': 'Charge Item',
                'verbose_name_plural': 'Charge Items',
                'db_table': 'accounting_charge_items',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='chg_item_doc_idx'), models.Index(fields=['definition'], name='chg_item_def_idx')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
