# Generated by Django 5.2.8 on 2026-09-06 04:36

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_chargedefinition_chargeitem'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountConfiguration',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='dcfg_', primary_key=True, serialize=False)),
                ('code', core.base_models.fields.char_fields.CustomCharField(help_text='Unique discount configuration code per company e.g. LADIES_10, SENIOR_15', max_length=50)),
                ('title', core.base_models.fields.char_fields.CustomCharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Of Subtotal'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', max_length=30)),
                ('is_global', models.BooleanField(default=False, help_text='True = global/system-managed; False = manual with explicit condition and tax arrays')),
                ('is_active', models.BooleanField(default=True)),
                ('conditions_payload', models.JSONField(blank=True, default=list, help_text='Snapshot of the manually passed conditions array (manual discounts)')),
                ('taxes_payload', models.JSONField(blank=True, default=list, help_text='Snapshot of the manually passed tax item keys array (manual discounts)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_configurations', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Discount Configuration',
                'verbose_name_plural': 'Discount Configurations',
                'db_table': 'accounting_discount_configurations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='chargedefinition',
            name='discount_configuration',
            field=models.ForeignKey(blank=True, help_text='Opt-in discount config that drives automatic DISCOUNT charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='accounting.discountconfiguration'),
        ),
        migrations.CreateModel(
            name='DiscountConditionItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='dcond_', primary_key=True, serialize=False)),
                ('field_key', core.base_models.fields.char_fields.CustomCharField(help_text='Runtime attribute name evaluated on the target, e.g. gender, age, loyalty_tier', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('operator', models.CharField(choices=[('EQUAL_TO', 'Equal To'), ('NOT_EQUAL_TO', 'Not Equal To'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('GREATER_THAN_OR_EQUAL', 'Greater Than Or Equal To'), ('LESS_THAN_OR_EQUAL', 'Less Than Or Equal To'), ('BETWEEN', 'Between Value 1 And Value 2')], default='EQUAL_TO', max_length=30)),
                ('value', models.CharField(blank=True, default='', help_text='Comparison value 1 (e.g. "Female", 21, "Gold")', max_length=120)),
                ('value_to', models.CharField(blank=True, default='', help_text='Comparison value 2 for BETWEEN / range operators (e.g. greater than 1, less than 2)', max_length=120)),
                ('percentage', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0, help_text='Discount percentage awarded when the condition matches', max_digits=5)),
                ('fixed_amount', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0, help_text='Fixed discount amount awarded when the condition matches (FIXED_AMOUNT configs)', max_digits=12)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of the condition inside its array')),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Generic FK to the attribute source entity (Gender, Segment, Category, Product)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='accounting.discountconfiguration')),
            ],
            options={
                'verbose_name': 'Discount Condition',
                'verbose_name_plural': 'Discount Conditions',
                'db_table': 'accounting_discount_conditions',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['configuration', 'field_key'], name='disc_cond_key_idx'), models.Index(fields=['content_type', 'object_id'], name='disc_cond_target_idx')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiscountTaxItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='dtax_', primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='accounting.discountconfiguration')),
                ('item_tax_template', models.ForeignKey(help_text='Item tax template the discount applies through', on_delete=django.db.models.deletion.PROTECT, related_name='discount_tax_items', to='accounting.itemtaxtemplate')),
            ],
            options={
                'verbose_name': 'Discount Tax Item',
                'verbose_name_plural': 'Discount Tax Items',
                'db_table': 'accounting_discount_taxes',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('configuration', 'item_tax_template'), name='unique_discount_tax_item')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
