# Generated by Django 5.2.8 on 2026-09-06 04:59

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_discountconfiguration_and_more'),
        ('core_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRatePack',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='tpk_', primary_key=True, serialize=False)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO-3166 alpha-2 country the branch ships from, e.g. AE / US / IN', max_length=2)),
                ('code', core.base_models.fields.char_fields.CustomCharField(help_text='Unique tax pack code per company, e.g. AE_VAT_18, US_SF_SALES_TAX', max_length=50)),
                ('title', core.base_models.fields.char_fields.CustomCharField(help_text='e.g. UAE Standard VAT 18%, California Sales Tax 7.25%', max_length=150)),
                ('direction', models.CharField(choices=[('SALES', 'Sales Taxes'), ('PURCHASE', 'Purchase Taxes'), ('ITEM', 'Item Taxes'), ('BOTH', 'Sales And Purchase')], default='BOTH', max_length=30)),
                ('tax_category', models.CharField(choices=[('VAT', 'Value Added Tax (VAT)'), ('GST', 'Goods and Services Tax (GST)'), ('SALES_TAX', 'Standard Sales Tax'), ('EXCISE', 'Excise Duty'), ('ZERO_RATED', 'Zero Rated / Exempt')], default='VAT', max_length=30)),
                ('is_inclusive', models.BooleanField(default=False, help_text="If true, item prices already include this pack's tax amounts")),
                ('is_default', models.BooleanField(default=False, help_text='Preferred pack for this company when none matches the branch')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the pack applies to; literal `None` = company-wide fallback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_rate_packs', to='core_admin.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rate_packs', to='core_admin.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_rate_packs', to='accounting.currency')),
            ],
            options={
                'verbose_name': 'Tax Rate Pack',
                'verbose_name_plural': 'Tax Rate Packs',
                'db_table': 'accounting_tax_rate_packs',
                'ordering': ['country_code', 'code'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='chargedefinition',
            name='tax_pack',
            field=models.ForeignKey(blank=True, help_text='Branch/country tax pack used when no explicit tax template is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='accounting.taxratepack'),
        ),
        migrations.CreateModel(
            name='TaxRatePackLine',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='tpkl_', primary_key=True, serialize=False)),
                ('tax_name', core.base_models.fields.char_fields.CustomCharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Tax percentage rate e.g. 18.000', max_digits=6)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(help_text='GL Tax Payable account credited for this line', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rate_pack_lines', to='accounting.account')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='accounting.taxratepack')),
            ],
            options={
                'verbose_name': 'Tax Pack Line',
                'verbose_name_plural': 'Tax Pack Lines',
                'db_table': 'accounting_tax_rate_pack_lines',
                'ordering': ['position', 'created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
