# Generated by Django 5.2.8 on 2026-09-06 05:12

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_tax_packs_and_operator_registry'),
        ('core_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, prefix='tcode_', primary_key=True, serialize=False)),
                ('code', core.base_models.fields.char_fields.CustomCharField(help_text='Fiscal / internal tax code, e.g. VAT_AE_5, STATE_CA_4_5, ENV_FEE_0_5', max_length=50)),
                ('title', core.base_models.fields.char_fields.CustomCharField(help_text='e.g. UAE Federal VAT, California State Sales Tax', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax (VAT)'), ('GST', 'Goods and Services Tax (GST)'), ('SALES_TAX', 'Standard Sales Tax'), ('EXCISE', 'Excise Duty'), ('ZERO_RATED', 'Zero Rated / Exempt')], default='VAT', help_text='Tax regime classification of this code', max_length=30)),
                ('jurisdiction', models.CharField(choices=[('FEDERAL', 'Federal / National'), ('STATE', 'State / Province / Emirate'), ('LOCAL', 'Local / Municipal')], default='FEDERAL', help_text='Federal / State / Local authority that levies this tax', max_length=30)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO-3166 alpha-2 country of the levying authority, e.g. AE / US / IN', max_length=2)),
                ('base_rate', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=3, default=0, help_text='Nominal rate of the code, e.g. 0.920 for 9.2%', max_digits=6)),
                ('is_compound', models.BooleanField(default=False, help_text='True when this tax stacks on top of other taxes (tax on tax)')),
                ('is_recoverable', models.BooleanField(default=True, help_text='True when input tax can be reclaimed (credit eligible)')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Tax Code',
                'verbose_name_plural': 'Tax Codes',
                'db_table': 'accounting_tax_codes',
                'ordering': ['country_code', 'jurisdiction', 'code'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='tcmp_', primary_key=True, serialize=False)),
                ('code', core.base_models.fields.char_fields.CustomCharField(help_text='Unique component code per company, e.g. VAT_18, STATE_CA_4_5', max_length=50)),
                ('tax_name', core.base_models.fields.char_fields.CustomCharField(help_text='e.g. Federal VAT 18%, State Sales Tax 4.5%', max_length=100)),
                ('rate', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=3, default=0, help_text='Charged percentage rate, e.g. 18.000', max_digits=6)),
                ('is_inclusive', models.BooleanField(default=False, help_text="If true, item prices already include this component's tax")),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(help_text='GL tax payable account credited when this component is charged', on_delete=django.db.models.deletion.PROTECT, related_name='tax_components', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_components', to='core_admin.company')),
                ('tax_code', models.ForeignKey(help_text='Fiscal identity this component charges against', on_delete=django.db.models.deletion.PROTECT, related_name='tax_components', to='accounting.taxcode')),
            ],
            options={
                'verbose_name': 'Tax Component',
                'verbose_name_plural': 'Tax Components',
                'db_table': 'accounting_tax_components',
                'ordering': ['code'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaxPackComponent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='tpcm_', primary_key=True, serialize=False)),
                ('tax_name', core.base_models.fields.char_fields.CustomCharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Tax percentage rate charged by this pack line, e.g. 18.000', max_digits=6)),
                ('group', models.CharField(choices=[('FEDERAL', 'Federal Group'), ('STATE', 'State Group'), ('LOCAL', 'Local Group'), ('ENVIRONMENTAL', 'Environmental / Fee'), ('EXEMPT', 'Exempt / Zero Rated'), ('OTHER', 'Other Group')], default='OTHER', help_text='Structural group (Federal / State / Local / Fee) for breakdowns', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(help_text='GL Tax Payable account credited for this line', on_delete=django.db.models.deletion.PROTECT, related_name='tax_pack_components', to='accounting.account')),
                ('component', models.ForeignKey(help_text='Reusable tax component structured into this pack', on_delete=django.db.models.deletion.PROTECT, related_name='pack_components', to='accounting.taxcomponent')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='accounting.taxratepack')),
            ],
            options={
                'verbose_name': 'Tax Pack Component',
                'verbose_name_plural': 'Tax Pack Components',
                'db_table': 'accounting_tax_pack_components',
                'ordering': ['position', 'created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='TaxRatePackLine',
        ),
        migrations.AddIndex(
            model_name='taxcode',
            index=models.Index(fields=['country_code', 'jurisdiction'], name='tax_code_jur_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcomponent',
            index=models.Index(fields=['tax_code'], name='tax_comp_code_idx'),
        ),
    ]
