# Generated by Django 5.2.8 on 2026-09-06 05:25

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_tax_codes_and_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpackcomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='taxpackcomponent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='taxpackcomponent',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='base_rate',
        ),
        migrations.AddField(
            model_name='taxcode',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GL tax payable account credited when this code is charged', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='is_inclusive',
            field=models.BooleanField(default=False, help_text="If true, item prices already include this code's tax"),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='rate',
            field=core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=3, default=0, help_text='Charged percentage rate, e.g. 18.000', max_digits=6),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='code',
            field=core.base_models.fields.char_fields.CustomCharField(help_text='Fiscal / internal tax code, e.g. FED_VAT_AE_5, STATE_CA_4_5, MUNI_1_5', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='jurisdiction',
            field=models.CharField(choices=[('FEDERAL', 'Federal / National'), ('STATE', 'State / Province / Emirate'), ('LOCAL', 'Local / Municipal')], default='FEDERAL', help_text='Federal / State / Local (municipal) authority that levies this tax', max_length=30),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='title',
            field=core.base_models.fields.char_fields.CustomCharField(help_text='e.g. UAE Federal VAT, California State Sales Tax, Dubai Municipality Fee', max_length=150),
        ),
        migrations.CreateModel(
            name='TaxPackCode',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='tpkl_', primary_key=True, serialize=False)),
                ('tax_name', core.base_models.fields.char_fields.CustomCharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Tax percentage rate charged by this pack line, e.g. 18.000', max_digits=6)),
                ('group', models.CharField(choices=[('FEDERAL', 'Federal Group'), ('STATE', 'State Group'), ('LOCAL', 'Local Group'), ('ENVIRONMENTAL', 'Environmental / Fee'), ('EXEMPT', 'Exempt / Zero Rated'), ('OTHER', 'Other Group')], default='OTHER', help_text='Structural group (FEDERAL / STATE / LOCAL / EXEMPT / FEE) for breakdowns', max_length=30)),
                ('is_inclusive', models.BooleanField(default=False, help_text="Per-pack: whether this code's tax is embedded in prices here")),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(help_text='GL Tax Payable account credited for this line', on_delete=django.db.models.deletion.PROTECT, related_name='tax_pack_lines', to='accounting.account')),
                ('code', models.ForeignKey(help_text='Chargeable tax code structured into this pack', on_delete=django.db.models.deletion.PROTECT, related_name='pack_lines', to='accounting.taxcode')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='accounting.taxratepack')),
            ],
            options={
                'verbose_name': 'Tax Pack Line',
                'verbose_name_plural': 'Tax Pack Lines',
                'db_table': 'accounting_tax_pack_lines',
                'ordering': ['position', 'created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='TaxComponent',
        ),
        migrations.DeleteModel(
            name='TaxPackComponent',
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='account',
            field=models.ForeignKey(help_text='GL tax payable account credited when this code is charged', on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounting.account'),
        ),
    ]
