# Generated by Django 5.2.8 on 2026-06-03 07:41

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.mixins.related
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('key', core.base_models.fields.char_fields.CustomCharField(max_length=50)),
                ('label', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('prefix', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('expires', models.BooleanField(default=False)),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('company', core.base_models.fields.mixins.related.RulesForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_definitions', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Document Definition',
                'verbose_name_plural': 'Document Definitions',
                'db_table': 'core_documents_definitions',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('object_id', models.CharField(max_length=50)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core_documents.documentdefinition')),
            ],
            options={
                'db_table': 'documents',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core_documents.document')),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['document', '-version'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
