# Generated by Django 5.2.8 on 2026-09-06 04:15

import apps.core_documents.models.documents
import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.permissions
import core.base_models.validator_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level_number', models.PositiveIntegerField(help_text='Sequence position of the approval level')),
                ('label', models.CharField(help_text="Label of the level, e.g. 'Department Manager'", max_length=100)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Action taken', max_length=20)),
                ('actioned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the action')),
                ('comments', models.TextField(blank=True, help_text='Comments or rejection feedback', null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the policy/rules during this action')),
            ],
            options={
                'db_table': 'document_approval_history',
                'ordering': ['-actioned_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level_number', models.PositiveIntegerField(help_text='Sequence position of this approval level (1-indexed)')),
                ('label', models.CharField(help_text="Human-readable label for this level, e.g., 'Department Manager'", max_length=100)),
                ('required_permission', models.CharField(help_text='The permission code required by the actor to sign off this level', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Sign-off status of this specific level', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, help_text='Timestamp when the action was performed', null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments or rejection feedback from the sign-off actor', null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority ordering for parallel levels at the same sequence step.')),
            ],
            options={
                'db_table': 'document_approval_levels',
                'ordering': ['workflow', 'level_number', '-priority', 'id'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('current_level', models.PositiveIntegerField(default=1, help_text='The current active level number in the chain')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The overall status of this approval workflow', max_length=20)),
            ],
            options={
                'db_table': 'document_approval_workflows',
                'ordering': ['-created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('object_id', models.CharField(max_length=50)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, help_text='Calculated date of document expiration', null=True)),
                ('alert_sent', models.BooleanField(default=False, help_text='Flag indicating if expiration alert has been dispatched')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current lifecycle state of the document', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason document was rejected, if applicable', null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='Timestamp of the last state transition', null=True)),
            ],
            options={
                'db_table': 'documents',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('key', core.base_models.fields.char_fields.CustomCharField(max_length=50)),
                ('label', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('prefix', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('expires', models.BooleanField(default=False)),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('max_file_size', models.PositiveIntegerField(blank=True, help_text='Maximum allowed file size in bytes', null=True)),
                ('allowed_mime_types', models.JSONField(blank=True, default=list, help_text="List of allowed MIME types, e.g. ['application/pdf']")),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text="List of allowed file extensions, e.g. ['.pdf']")),
                ('expiry_notification_days', models.PositiveIntegerField(default=30, help_text='Number of days before expiry to send an alert')),
                ('approval_chain_config', models.JSONField(blank=True, default=list, help_text='Configured approval levels for documents of this type')),
            ],
            options={
                'verbose_name': 'Document Definition',
                'verbose_name_plural': 'Document Definitions',
                'db_table': 'core_documents_definitions',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=512, storage=apps.core_documents.models.documents.get_tenant_storage, upload_to=apps.core_documents.models.documents.get_upload_path)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['document', '-version'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
