# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.fields.mixins.related
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
        ('core_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='actor',
            field=models.ForeignKey(help_text='The user who took the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='actioned_by',
            field=models.ForeignKey(blank=True, help_text='The user who approved or rejected this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core_documents.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='workflow',
            field=models.ForeignKey(help_text='The associated workflow', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core_documents.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the last state transition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core_documents.document'),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='company',
            field=core.base_models.fields.mixins.related.RulesForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_definitions', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core_documents.documentdefinition'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core_documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentdefinition',
            constraint=models.UniqueConstraint(fields=('key', 'company'), name='unique_key_per_company_v2'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_content_7d700d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_version_v2'),
        ),
    ]
