# Generated by Django 5.2.8 on 2026-09-05 05:54

import apps.core_documents.models.documents
import core.base_models.audit_mixin
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='alert_sent',
            field=models.BooleanField(default=False, help_text='Flag indicating if expiration alert has been dispatched'),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Calculated date of document expiration', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason document was rejected, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current lifecycle state of the document', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last state transition', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the last state transition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='allowed_extensions',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed file extensions, e.g. ['.pdf']"),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='allowed_mime_types',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed MIME types, e.g. ['application/pdf']"),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='approval_chain_config',
            field=models.JSONField(blank=True, default=list, help_text='Configured approval levels for documents of this type'),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='expiry_notification_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days before expiry to send an alert'),
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed file size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=512, storage=apps.core_documents.models.documents.get_tenant_storage, upload_to=apps.core_documents.models.documents.get_upload_path),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('current_level', models.PositiveIntegerField(default=1, help_text='The current active level number in the chain')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The overall status of this approval workflow', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core_documents.document')),
            ],
            options={
                'db_table': 'document_approval_workflows',
                'ordering': ['-created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level_number', models.PositiveIntegerField(help_text='Sequence position of this approval level (1-indexed)')),
                ('label', models.CharField(help_text="Human-readable label for this level, e.g., 'Department Manager'", max_length=100)),
                ('required_permission', models.CharField(help_text='The permission code required by the actor to sign off this level', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Sign-off status of this specific level', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, help_text='Timestamp when the action was performed', null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments or rejection feedback from the sign-off actor', null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority ordering for parallel levels at the same sequence step.')),
                ('actioned_by', models.ForeignKey(blank=True, help_text='The user who approved or rejected this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_levels', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core_documents.approvalworkflow')),
            ],
            options={
                'db_table': 'document_approval_levels',
                'ordering': ['workflow', 'level_number', '-priority', 'id'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level_number', models.PositiveIntegerField(help_text='Sequence position of the approval level')),
                ('label', models.CharField(help_text="Label of the level, e.g. 'Department Manager'", max_length=100)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Action taken', max_length=20)),
                ('actioned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the action')),
                ('comments', models.TextField(blank=True, help_text='Comments or rejection feedback', null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the policy/rules during this action')),
                ('actor', models.ForeignKey(help_text='The user who took the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The associated workflow', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core_documents.approvalworkflow')),
            ],
            options={
                'db_table': 'document_approval_history',
                'ordering': ['-actioned_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
