# Generated by Django 5.2.8 on 2026-09-06 04:16

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_initial'),
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('gateway_type', core.base_models.fields.char_fields.CustomCharField(choices=[('RAZORPAY', 'Razorpay Payment Gateway'), ('PAYPAL', 'PayPal Express Checkout'), ('STRIPE', 'Stripe Credit Card Gateway'), ('COD', 'Cash on Delivery')], max_length=30, unique=True)),
                ('display_name', core.base_models.fields.char_fields.CustomCharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('supported_currencies', models.JSONField(blank=True, default=list)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
                'db_table': 'payment_gateway_configs',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=36, prefix='tx_', primary_key=True, serialize=False)),
                ('transaction_code', core.base_models.fields.char_fields.CustomCharField(max_length=60, unique=True)),
                ('gateway_type', models.CharField(choices=[('RAZORPAY', 'Razorpay Payment Gateway'), ('PAYPAL', 'PayPal Express Checkout'), ('STRIPE', 'Stripe Credit Card Gateway'), ('COD', 'Cash on Delivery')], max_length=30)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('PENDING', 'Pending Customer Action'), ('AUTHORIZED', 'Payment Authorized'), ('CAPTURED', 'Payment Successfully Captured'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled'), ('REFUNDED', 'Payment Fully Refunded'), ('PARTIALLY_REFUNDED', 'Payment Partially Refunded')], db_index=True, default='INITIATED', max_length=30)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='rfnd_', primary_key=True, serialize=False)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PROCESSED', max_length=30)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payment_refunds',
                'ordering': ['-created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
