# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.boolean_fields
import core.base_models.fields.char_fields
import core.base_models.fields.date_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import core.base_models.validators.email_validator
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, length=35, max_length=42, primary_key=True, serialize=False, unique=True)),
                ('email', core.base_models.fields.char_fields.CustomEmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address with a proper domain.', regex='^[\\w\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$'), core.base_models.validators.email_validator.validate_email_domain], verbose_name='Email Address')),
                ('username', core.base_models.fields.char_fields.CustomCharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Username')),
                ('full_name', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('is_active', core.base_models.fields.boolean_fields.CustomBooleanField(default=True)),
                ('is_staff', core.base_models.fields.boolean_fields.CustomBooleanField(default=False)),
                ('date_joined', core.base_models.fields.date_fields.CustomDateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            bases=(models.Model, core.base_models.validator_model.ValidatorModelMixin),
        ),
        migrations.CreateModel(
            name='BranchCatalog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Catalog Name')),
                ('description', models.TextField(blank=True)),
                ('module_keys', models.JSONField(blank=True, default=list, help_text='Aggregation of systems included in this catalog')),
                ('allowed_permission_keys', models.JSONField(blank=True, default=list, help_text='Subset of all possible permission keys allowed for this subscription')),
            ],
            options={
                'verbose_name': 'Branch Catalog',
                'verbose_name_plural': 'Branch Catalogs',
                'db_table': 'branch_catalogs',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True)),
                ('permission_keys', models.JSONField(blank=True, default=list, help_text='List of technical permission keys (e.g., resource:action)')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoleGroupPermissions',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('permission_keys', models.JSONField(blank=True, default=list, help_text='Bulk permission keys assigned directly to this group')),
                ('roles', models.ManyToManyField(blank=True, related_name='role_groups', to='users.rolepermissions')),
            ],
            options={
                'verbose_name': 'Role Group',
                'verbose_name_plural': 'Role Groups',
                'db_table': 'role_group_permissions',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('direct_permissions', models.JSONField(blank=True, default=list, help_text='Direct permission key overrides for this specific user')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_assignments', to='users.rolegrouppermissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_assignments', to='users.rolepermissions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permission_assignments',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('STAFF', 'Internal Staff / Employee'), ('CUSTOMER_B2C', 'Retail Customer (B2C)'), ('CUSTOMER_B2B', 'Corporate Customer (B2B)'), ('PARTNER_B2C', 'Affiliate / B2C Partner'), ('PARTNER_B2B', 'Vendor / Supplier / B2B Partner')], default='STAFF', help_text='Categorizes user into Staff, B2C/B2B Customer, or B2C/B2B Partner', max_length=30)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core_admin.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
