# Generated by Django 5.2.8 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Internal Staff / Employee'), ('CUSTOMER_B2C', 'Retail Customer (B2C)'), ('CUSTOMER_B2B', 'Corporate Customer (B2B)'), ('PARTNER_B2C', 'Affiliate / B2C Partner'), ('PARTNER_B2B', 'Vendor / Supplier / B2B Partner')], default='STAFF', help_text='Categorizes user into Staff, B2C/B2B Customer, or B2C/B2B Partner', max_length=30),
        ),
    ]
