from enum import StrEnum


class ProcurementKeys(StrEnum):
    PR_STATUS_DRAFT = "DRAFT"
    PR_STATUS_SUBMITTED = "SUBMITTED"
    PR_STATUS_APPROVED = "APPROVED"
    RFQ_STATUS_DRAFT = "DRAFT"
    RFQ_STATUS_PUBLISHED = "PUBLISHED"
    PO_STATUS_DRAFT = "DRAFT"
    PO_STATUS_SUBMITTED = "SUBMITTED"
    PO_STATUS_APPROVED = "APPROVED"
    PO_STATUS_COMPLETED = "COMPLETED"
    PO_STATUS_CANCELLED = "CANCELLED"
    GRN_STATUS_DRAFT = "DRAFT"
    GRN_STATUS_COMPLETED = "COMPLETED"
    INVOICE_STATUS_DRAFT = "DRAFT"
    INVOICE_STATUS_MATCHED = "MATCHED"
    INVOICE_STATUS_MISMATCH = "MISMATCH"


class POSKeys(StrEnum):
    SESSION_STATUS_OPEN = "OPEN"
    SESSION_STATUS_CLOSED = "CLOSED"
    TRANSACTION_STATUS_COMPLETED = "COMPLETED"
    PAYMENT_METHOD_CASH = "CASH"
    PAYMENT_METHOD_CARD = "CARD"
    PAYMENT_METHOD_UPI = "UPI"
