# Generated by Django 5.2.8 on 2026-06-03 11:58

import core.base_models.audit_mixin
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAccessControl',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', models.ForeignKey(blank=True, help_text='Optional: Elevate or restrict permissions within this specific entity scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolepermissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Access Control',
                'verbose_name_plural': 'Master Access Controls',
                'db_table': 'master_access_control',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='master_acce_content_dadd19_idx'), models.Index(fields=['user', 'content_type', 'object_id'], name='master_acce_user_id_d5fcc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_entity_access')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
