# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('escalate', 'Escalate'), ('comment', 'Comment')], max_length=20, verbose_name='Action Type')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('level', models.PositiveIntegerField(help_text='Which approval level this action was taken at.', verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'approval_actions',
                'ordering': ['created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Friendly name (e.g. IT Department Leave Approval).', max_length=100, verbose_name='Name')),
                ('approval_type', models.CharField(help_text="Identifier for the type of request (e.g. 'invoice', 'purchase_order')", max_length=100, verbose_name='Approval Type')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="JSON-based matching rules (e.g. {'amount_gt': 5000})", verbose_name='Conditions')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority chains are evaluated first.', verbose_name='Priority')),
                ('allow_higher_level_override', models.BooleanField(default=True, help_text='Allows senior approvers to approve requests pending at lower levels.', verbose_name='Allow Higher-Level Override')),
                ('domain_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domain Object ID')),
                ('chain_auto_action', models.CharField(choices=[('null', 'Level Based'), ('approve', 'Auto Approve'), ('reject', 'Auto Reject')], default='null', max_length=20, verbose_name='Chain Auto Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
                'db_table': 'approval_chains',
                'ordering': ['-priority'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level', models.PositiveIntegerField(help_text='Approval level number (1, 2, 3...).', verbose_name='Level')),
                ('approver_by_type', models.CharField(choices=[('specific_user', 'Specific User'), ('role', 'Role')], max_length=50, verbose_name='Approver By')),
                ('approver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fallback_approver_by_type', models.CharField(choices=[('specific_user', 'Specific User'), ('role', 'Role')], max_length=50, verbose_name='Fallback Approver By')),
                ('fallback_approver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('allow_direct_approval', models.BooleanField(default=False, help_text='Allows finalizing the request instantly at this level.', verbose_name='Allow Direct Approval')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optional')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (Hours)')),
                ('timeout_action', models.CharField(choices=[('none', 'Do Nothing'), ('auto_approve', 'Auto Approve'), ('auto_reject', 'Auto Reject'), ('escalate', 'Escalate to Next Level')], default='none', max_length=20, verbose_name='Timeout Action')),
                ('can_edit_request', models.BooleanField(default=False, verbose_name='Can Edit Request')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority ordering for parallel levels at the same sequence step.', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'db_table': 'approval_levels',
                'ordering': ['level'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('object_id', models.CharField(max_length=50, verbose_name='Request ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='Status')),
                ('current_level', models.PositiveIntegerField(default=1, help_text='Which approval level this request is currently at.', verbose_name='Current Level')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of the request data at submission time.', verbose_name='Payload')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Decision Comment')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_requests',
                'ordering': ['-submitted_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Department name (e.g. HR, Finance, Cardiology).', max_length=150, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique code for department (e.g. HR, CARD, ENG).', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the department.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'access_control_departments',
                'ordering': ['name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Designation name (e.g. Lead Engineer, Product Manager).', max_length=150, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique code for designation (e.g. LE, PM).', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the designation.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'db_table': 'access_control_designations',
                'ordering': ['name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntityAccessControl',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Access Control',
                'verbose_name_plural': 'Master Access Controls',
                'db_table': 'master_access_control',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldAccessControl',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(help_text='The exact name of the column/field to restrict.', max_length=100)),
                ('can_read', models.BooleanField(default=True, help_text='If false, the field is stripped from all API responses.')),
                ('can_write', models.BooleanField(default=False, help_text='If false, the field is marked read-only on all forms.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Field Access Control',
                'verbose_name_plural': 'Field Access Controls',
                'db_table': 'field_access_control',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldAccessPolicy',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Unique name of the policy.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('field_name', models.CharField(help_text='The exact name of the column/field to restrict.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Field Access Policy',
                'verbose_name_plural': 'Field Access Policies',
                'db_table': 'field_access_policies',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PolicyConfiguration',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject_id', models.CharField(max_length=50)),
                ('action', models.CharField(default='read', help_text="Action to control: 'read', 'write', 'mask', etc.", max_length=50)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', help_text="Effect of the policy: 'allow' or 'deny'.", max_length=20)),
                ('scope_id', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON-based conditional rules for dynamic policy matching.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Policy Configuration',
                'verbose_name_plural': 'Policy Configurations',
                'db_table': 'policy_configurations',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PolicySnapshot',
            fields=[
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Policy Snapshot',
                'verbose_name_plural': 'Policy Snapshots',
                'db_table': 'policy_snapshots',
                'ordering': ['-version'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
