# Generated by Django 5.2.8 on 2026-06-03 12:08

import core.base_models.audit_mixin
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0003_alter_companyextension_options_branch_is_all_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Friendly name (e.g. IT Department Leave Approval).', max_length=100, verbose_name='Name')),
                ('approval_type', models.CharField(help_text="Identifier for the type of request (e.g. 'invoice', 'purchase_order')", max_length=100, verbose_name='Approval Type')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="JSON-based matching rules (e.g. {'amount_gt': 5000})", verbose_name='Conditions')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority chains are evaluated first.', verbose_name='Priority')),
                ('allow_higher_level_override', models.BooleanField(default=True, help_text='Allows senior approvers to approve requests pending at lower levels.', verbose_name='Allow Higher-Level Override')),
                ('domain_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domain Object ID')),
                ('chain_auto_action', models.CharField(choices=[('null', 'Level Based'), ('approve', 'Auto Approve'), ('reject', 'Auto Reject')], default='null', max_length=20, verbose_name='Chain Auto Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company')),
                ('domain_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='contenttypes.contenttype', verbose_name='Domain Object Type')),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
                'db_table': 'approval_chains',
                'ordering': ['-priority'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('level', models.PositiveIntegerField(help_text='Approval level number (1, 2, 3...).', verbose_name='Level')),
                ('approver_by_type', models.CharField(choices=[('specific_user', 'Specific User'), ('role', 'Role')], max_length=50, verbose_name='Approver By')),
                ('approver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fallback_approver_by_type', models.CharField(choices=[('specific_user', 'Specific User'), ('role', 'Role')], max_length=50, verbose_name='Fallback Approver By')),
                ('fallback_approver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('allow_direct_approval', models.BooleanField(default=False, help_text='Allows finalizing the request instantly at this level.', verbose_name='Allow Direct Approval')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optional')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (Hours)')),
                ('timeout_action', models.CharField(choices=[('none', 'Do Nothing'), ('auto_approve', 'Auto Approve'), ('auto_reject', 'Auto Reject'), ('escalate', 'Escalate to Next Level')], default='none', max_length=20, verbose_name='Timeout Action')),
                ('can_edit_request', models.BooleanField(default=False, verbose_name='Can Edit Request')),
                ('approver_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_approvers', to='contenttypes.contenttype')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='access_control.approvalchain', verbose_name='Approval Chain')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company')),
                ('fallback_approver_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_fallback_approvers', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'db_table': 'approval_levels',
                'ordering': ['level'],
                'unique_together': {('chain', 'level')},
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
