# Generated by Django 5.2.8 on 2026-09-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='domain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='contenttypes.contenttype', verbose_name='Domain Object Type'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='approver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_approvers', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='access_control.approvalchain', verbose_name='Approval Chain'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='fallback_approver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_fallback_approvers', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='access_control.approvalchain', verbose_name='Approval Chain'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Request Type'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='access_control.approvalrequest', verbose_name='Approval Request'),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_chains', to='access_control.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='designation',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_chains', to='access_control.designation', verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='entityaccesscontrol',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entityaccesscontrol',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Optional: Elevate or restrict permissions within this specific entity scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolepermissions'),
        ),
        migrations.AddField(
            model_name='entityaccesscontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldaccesscontrol',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fieldaccesscontrol',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_restrictions', to='users.rolepermissions'),
        ),
        migrations.AddField(
            model_name='fieldaccesscontrol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldaccesspolicy',
            name='approval_chain',
            field=models.ForeignKey(blank=True, help_text='Optional approval workflow to govern policy configuration changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.approvalchain'),
        ),
        migrations.AddField(
            model_name='fieldaccesspolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_policies', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='policyconfiguration',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='access_control.fieldaccesspolicy'),
        ),
        migrations.AddField(
            model_name='policyconfiguration',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_scopes', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='policyconfiguration',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_subjects', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='policysnapshot',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='access_control.fieldaccesspolicy'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'chain'], name='approval_re_status_1b8ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submitter', 'status'], name='approval_re_submitt_dcc29c_idx'),
        ),
        migrations.AddIndex(
            model_name='entityaccesscontrol',
            index=models.Index(fields=['content_type', 'object_id'], name='master_acce_content_dadd19_idx'),
        ),
        migrations.AddIndex(
            model_name='entityaccesscontrol',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='master_acce_user_id_d5fcc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityaccesscontrol',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_entity_access'),
        ),
        migrations.AddIndex(
            model_name='fieldaccesscontrol',
            index=models.Index(fields=['content_type', 'field_name'], name='field_acces_content_6d64e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldaccesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'content_type', 'field_name'), name='unique_user_field_access'),
        ),
        migrations.AddConstraint(
            model_name='fieldaccesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('role', 'content_type', 'field_name'), name='unique_role_field_access'),
        ),
        migrations.AddConstraint(
            model_name='policyconfiguration',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_policy_version'),
        ),
    ]
