# Generated by Django 5.2.8 on 2026-07-12 08:01

import core.base_models.audit_mixin
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_approvalchain_approvallevel'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0003_alter_companyextension_options_branch_is_all_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('object_id', models.CharField(max_length=50, verbose_name='Request ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='Status')),
                ('current_level', models.PositiveIntegerField(default=1, help_text='Which approval level this request is currently at.', verbose_name='Current Level')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of the request data at submission time.', verbose_name='Payload')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Decision Comment')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='access_control.approvalchain', verbose_name='Approval Chain')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Request Type')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_requests',
                'ordering': ['-submitted_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('escalate', 'Escalate'), ('comment', 'Comment')], max_length=20, verbose_name='Action Type')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('level', models.PositiveIntegerField(help_text='Which approval level this action was taken at.', verbose_name='Level')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='access_control.approvalrequest', verbose_name='Approval Request')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'approval_actions',
                'ordering': ['created_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'chain'], name='approval_re_status_1b8ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submitter', 'status'], name='approval_re_submitt_dcc29c_idx'),
        ),
    ]
