# Generated by Django 5.2.8 on 2026-09-05 05:54

import core.base_models.audit_mixin
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_approvalrequest_approvalaction_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0004_company_default_currency_numberseries'),
        ('users', '0002_userprofilemodel_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority ordering for parallel levels at the same sequence step.', verbose_name='Priority'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Department name (e.g. HR, Finance, Cardiology).', max_length=150, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique code for department (e.g. HR, CARD, ENG).', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the department.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'access_control_departments',
                'ordering': ['name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_chains', to='access_control.department', verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Designation name (e.g. Lead Engineer, Product Manager).', max_length=150, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique code for designation (e.g. LE, PM).', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the designation.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'db_table': 'access_control_designations',
                'ordering': ['name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_chains', to='access_control.designation', verbose_name='Designation'),
        ),
        migrations.CreateModel(
            name='FieldAccessPolicy',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Unique name of the policy.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('field_name', models.CharField(help_text='The exact name of the column/field to restrict.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_chain', models.ForeignKey(blank=True, help_text='Optional approval workflow to govern policy configuration changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.approvalchain')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_policies', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Field Access Policy',
                'verbose_name_plural': 'Field Access Policies',
                'db_table': 'field_access_policies',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PolicySnapshot',
            fields=[
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='access_control.fieldaccesspolicy')),
            ],
            options={
                'verbose_name': 'Policy Snapshot',
                'verbose_name_plural': 'Policy Snapshots',
                'db_table': 'policy_snapshots',
                'ordering': ['-version'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldAccessControl',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(help_text='The exact name of the column/field to restrict.', max_length=100)),
                ('can_read', models.BooleanField(default=True, help_text='If false, the field is stripped from all API responses.')),
                ('can_write', models.BooleanField(default=False, help_text='If false, the field is marked read-only on all forms.')),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_restrictions', to='users.rolepermissions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Access Control',
                'verbose_name_plural': 'Field Access Controls',
                'db_table': 'field_access_control',
                'indexes': [models.Index(fields=['content_type', 'field_name'], name='field_acces_content_6d64e5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'content_type', 'field_name'), name='unique_user_field_access'), models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('role', 'content_type', 'field_name'), name='unique_role_field_access')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PolicyConfiguration',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject_id', models.CharField(max_length=50)),
                ('action', models.CharField(default='read', help_text="Action to control: 'read', 'write', 'mask', etc.", max_length=50)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', help_text="Effect of the policy: 'allow' or 'deny'.", max_length=20)),
                ('scope_id', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON-based conditional rules for dynamic policy matching.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='access_control.fieldaccesspolicy')),
                ('scope_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_scopes', to='contenttypes.contenttype')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_subjects', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Policy Configuration',
                'verbose_name_plural': 'Policy Configurations',
                'db_table': 'policy_configurations',
                'constraints': [models.UniqueConstraint(fields=('policy', 'version'), name='unique_policy_version')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
