# Generated by Django 5.2.8 on 2026-09-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_admin', '0002_initial'),
        ('procurement_pos', '0003_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement_pos.supplier'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category'),
        ),
        migrations.AddField(
            model_name='categoryedge',
            name='from_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='shop.category'),
        ),
        migrations.AddField(
            model_name='categoryedge',
            name='to_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='shop.category'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to='core_admin.company'),
        ),
        migrations.AddIndex(
            model_name='domaineventoutbox',
            index=models.Index(fields=['status', 'created_at'], name='shop_domain_status_c740bc_idx'),
        ),
        migrations.AddIndex(
            model_name='domaineventoutbox',
            index=models.Index(fields=['event_type'], name='shop_domain_event_t_a19816_idx'),
        ),
        migrations.AddField(
            model_name='entityedge',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_graph_edges', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entityedge',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_graph_edges', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='facilityinventory',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='shop.facility'),
        ),
        migrations.AddField(
            model_name='facilitypolicyrule',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_policy_rules', to='shop.deliverypartner'),
        ),
        migrations.AddField(
            model_name='facilitypolicyrule',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Null applies rule globally to all facilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='shop.facility'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='shop.batch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='valuation_currency',
            field=models.ForeignKey(blank=True, help_text='Inventory valuation cost currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_tax_template',
            field=models.ForeignKey(blank=True, help_text='Product-specific tax rate template overrides', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounting.itemtaxtemplate'),
        ),
        migrations.AddField(
            model_name='product',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_inventory_records', to='shop.product'),
        ),
        migrations.AddField(
            model_name='facilityinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_inventory', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for nested self-referencing reply threads', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.productcomment'),
        ),
        migrations.AddField(
            model_name='producttestimonial',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='facilityinventory',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_inventory', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='bomedge',
            name='child_variant',
            field=models.ForeignKey(help_text='Component product variant', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parents', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='bomedge',
            name='parent_variant',
            field=models.ForeignKey(help_text='Assembly product variant', on_delete=django.db.models.deletion.CASCADE, related_name='bom_children', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='batch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='shop.batch'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='shop.facility'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='shop.storagelocation'),
        ),
        migrations.AddField(
            model_name='facilityinventory',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='shop.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='shop.warehouse'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_activi_content_ad3449_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryedge',
            unique_together={('from_category', 'to_category', 'relation_type')},
        ),
        migrations.AddIndex(
            model_name='entityedge',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='shop_entity_source__ae68cb_idx'),
        ),
        migrations.AddIndex(
            model_name='entityedge',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='shop_entity_target__5af9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='entityedge',
            index=models.Index(fields=['relation_type'], name='shop_entity_relatio_1a7742_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_media_content_264578_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_produc_content_be40d9_idx'),
        ),
        migrations.AddIndex(
            model_name='producttestimonial',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_produc_content_6b4454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomedge',
            unique_together={('parent_variant', 'child_variant')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'object_id'], name='shop_review_content_d65ba5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('facility', 'location_code')},
        ),
        migrations.AlterUniqueTogether(
            name='facilityinventory',
            unique_together={('facility', 'storage_location', 'product', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('variant', 'warehouse', 'branch', 'batch')},
        ),
    ]
