# Generated by Django 5.2.8 on 2026-09-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_remove_category_description_and_more'),
        ('procurement_pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='procurement_pos.supplier',
            ),
        ),
    ]
