# Generated by Django 5.2.8 on 2026-09-05 05:54

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.numeric_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0004_company_default_currency_numberseries'),
        ('shop', '0003_batch_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=41, prefix='partner_', primary_key=True, serialize=False)),
                ('name', core.base_models.fields.char_fields.CustomCharField(help_text='e.g. FedEx Express, DHL Supply Chain, Hyperlocal Fleet', max_length=150)),
                ('partner_code', core.base_models.fields.char_fields.CustomCharField(max_length=50)),
                ('partner_type', models.CharField(choices=[('IN_HOUSE', 'In-House Delivery Fleet'), ('EXPRESS_COURIER', 'Express Courier (Same-Day / 30-Min)'), ('NATIONAL_CARRIER', 'National 3PL Carrier (FedEx/DHL)'), ('HYPERLOCAL', 'Hyperlocal Bike / EV Courier'), ('COLD_CHAIN', 'Cold Chain Refrigerated Fleet')], default='NATIONAL_CARRIER', max_length=30)),
                ('max_weight_capacity_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('supported_pincodes', models.JSONField(blank=True, default=list)),
                ('cutoff_time', models.TimeField(blank=True, help_text='Daily order dispatch cutoff time e.g. 17:00', null=True)),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='Tracking & Booking API Credentials')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Delivery Partner',
                'verbose_name_plural': 'Delivery Partners',
                'db_table': 'shop_delivery_partners',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacilityPolicyRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=38, prefix='fpol_', primary_key=True, serialize=False)),
                ('rule_name', core.base_models.fields.char_fields.CustomCharField(help_text='e.g. Cold Storage Mandatory Policy, Max Weight 50kg Limit', max_length=150)),
                ('max_order_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requires_cold_storage', models.BooleanField(default=False)),
                ('allow_hazmat', models.BooleanField(default=True)),
                ('dispatch_cutoff_time', models.TimeField(blank=True, null=True)),
                ('policy_conditions', models.JSONField(blank=True, default=dict, help_text="Custom rule evaluation conditions JSON e.g. {'min_order_value': 100}")),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_policy_rules', to='shop.deliverypartner')),
                ('facility', models.ForeignKey(blank=True, help_text='Null applies rule globally to all facilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='shop.facility')),
            ],
            options={
                'verbose_name': 'Facility Policy Rule',
                'verbose_name_plural': 'Facility Policy Rules',
                'db_table': 'shop_facility_policy_rules',
                'ordering': ['rule_name'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=37, prefix='ori_', primary_key=True, serialize=False)),
                ('quantity', core.base_models.fields.numeric_fields.CustomIntegerField(default=0)),
                ('unit_price', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('line_total', core.base_models.fields.numeric_fields.CustomDecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'shop_order_items',
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
