# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.boolean_fields
import core.base_models.fields.char_fields
import core.base_models.fields.json_fields
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('component_name', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Component Name')),
                ('status', core.base_models.fields.char_fields.CustomCharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Health Status')),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='Latency (ms)')),
                ('details', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=dict, verbose_name='Health Details')),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health Monitoring',
                'db_table': 'system_health',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('code', core.base_models.fields.char_fields.CustomCharField(max_length=50, unique=True, verbose_name='Module Code')),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=100, verbose_name='Module Name')),
                ('is_active', core.base_models.fields.boolean_fields.CustomBooleanField(default=True)),
                ('icon', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=50, null=True, verbose_name='Icon Name')),
                ('color', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=20, null=True, verbose_name='Display Color')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'db_table': 'system_modules',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('key', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Configuration Key')),
                ('value', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=255, null=True, verbose_name='Configuration Value')),
                ('description', models.TextField(blank=True, null=True)),
                ('details', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=dict, verbose_name='Configuration Details')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_base_models.systemconfig', verbose_name='Parent Group')),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
                'db_table': 'system_configs',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('code', core.base_models.fields.char_fields.CustomCharField(max_length=100, unique=True, verbose_name='Feature Code')),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=150, verbose_name='Feature Name')),
                ('model_name', core.base_models.fields.char_fields.CustomCharField(blank=True, max_length=100, null=True, verbose_name='Primary Model')),
                ('related_models', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=list, verbose_name='Related Models')),
                ('is_enabled', core.base_models.fields.boolean_fields.CustomBooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('special_permissions', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=list, verbose_name='Special Permissions')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core_base_models.systemmodule')),
            ],
            options={
                'verbose_name': 'System Feature',
                'verbose_name_plural': 'System Features',
                'db_table': 'system_features',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeatureDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_features', to='core_base_models.systemfeature')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_dependencies', to='core_base_models.systemfeature')),
            ],
            options={
                'verbose_name': 'Feature Dependency',
                'verbose_name_plural': 'Feature Dependencies',
                'db_table': 'feature_dependencies',
                'unique_together': {('feature', 'depends_on')},
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
