# Generated by Django 5.2.8 on 2026-09-06 04:15

import core.base_models.audit_mixin
import core.base_models.fields.char_fields
import core.base_models.fields.date_fields
import core.base_models.fields.json_fields
import core.base_models.fields.short_ui_fields
import core.base_models.permissions
import core.base_models.validator_model
import core.base_models.validators.email_validator
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('code', core.base_models.fields.char_fields.CustomCharField(max_length=20)),
                ('location', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('opened_date', core.base_models.fields.date_fields.CustomDateField()),
                ('is_all_branch', models.BooleanField(default=False, editable=False, help_text='System flag for the global all-encompassing Branch.')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'company_branches',
                'ordering': ['company', 'name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BranchExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'branch_extensions',
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=255)),
                ('code', core.base_models.fields.char_fields.CustomCharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_all_bu', models.BooleanField(default=False, editable=False, help_text='System flag for the global all-encompassing BU.')),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
                'db_table': 'company_business_units',
                'ordering': ['company', 'name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('id', core.base_models.fields.short_ui_fields.CustomShortUUIDField(editable=False, max_length=39, primary_key=True, serialize=False, unique=True)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=255, unique=True)),
                ('email', core.base_models.fields.char_fields.CustomEmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address with a proper domain.', regex='^[\\w\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$'), core.base_models.validators.email_validator.validate_email_domain])),
                ('code', core.base_models.fields.char_fields.CustomCharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
                'permissions': (('company:view', 'View Company'), ('company:create', 'Create Company'), ('company:edit', 'Edit Company'), ('company:delete', 'Delete Company'), ('company:import', 'Import Company Data'), ('company:export', 'Export Company Data'), ('company:audit', 'Audit Company Logs'), ('company:manage', 'Manage Company'), ('company:can_get_analytics', 'Get Company Analytics'), ('company:can_manage_ledger', 'Manage Company Ledger')),
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('extra_documents', models.JSONField(blank=True, default=list)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'company_extensions',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('document_type', models.CharField(db_index=True, help_text="Logical type identifier, e.g. 'vendor', 'purchase_order'.", max_length=100)),
                ('pattern', models.CharField(help_text="Pattern for generated codes, e.g. 'VEN-{YYYY}{MM}-{SEQ:5}'. Supported tokens: {YYYY}, {YY}, {MM}, {DD}, {COMPANY_CODE}, {BU_CODE}, {BRANCH_CODE}, {SEQ}, {SEQ:n}.", max_length=255)),
                ('current_number', models.BigIntegerField(default=0, help_text='Last used sequence number for this series.')),
                ('number_length', models.PositiveIntegerField(default=5, help_text='Default zero-padding length for {SEQ} when no explicit length is given.')),
                ('reset_policy', models.CharField(choices=[('NEVER', 'Never'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='NEVER', help_text='When to reset the sequence counter.', max_length=16)),
                ('last_reset_at', models.DateTimeField(blank=True, help_text='Last time the sequence was reset (stored in UTC).', null=True)),
                ('prefix', models.CharField(blank=True, default='', help_text='Static string to prepend to the generated number.', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', help_text='Static string to append to the generated number.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this number series is currently active.')),
            ],
            options={
                'verbose_name': 'Number Series',
                'verbose_name_plural': 'Number Series',
                'db_table': 'core_number_series',
                'abstract': False,
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('name', core.base_models.fields.char_fields.CustomCharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('licenses', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=dict)),
                ('modules', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=list)),
                ('pricing', core.base_models.fields.json_fields.CustomJSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'saas_subscriptions',
                'ordering': ['name'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saas_subscription_attributes',
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('module', models.CharField(default='all', max_length=255)),
                ('category', models.CharField(default='all', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changes', models.JSONField(default=dict, help_text='JSON payload of changed fields and their old/new values.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
