# Generated by Django 5.2.8 on 2026-09-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core_admin', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='catalog',
            field=models.ForeignKey(blank=True, help_text='The subscription tier/catalog applied to this branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_branches', to='users.branchcatalog'),
        ),
        migrations.AddField(
            model_name='branchextension',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Company base General Ledger reporting currency e.g. USD, SAR, EUR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_using_base', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='companyextension',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='numberseries',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.branch'),
        ),
        migrations.AddField(
            model_name='numberseries',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.businessunit'),
        ),
        migrations.AddField(
            model_name='numberseries',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core_admin.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionattribute',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core_admin.subscription'),
        ),
        migrations.AddField(
            model_name='systemlogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_entri_content_14003e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['action'], name='audit_entri_action_db6795_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_bu_per_company'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_branch_per_company'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['document_type'], name='core_number_documen_7b462e_idx'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['document_type', 'company'], name='core_number_documen_a39d88_idx'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['document_type', 'company', 'business_unit'], name='core_number_documen_9c4c78_idx'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['document_type', 'company', 'business_unit', 'branch'], name='core_number_documen_d7fecc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionattribute',
            index=models.Index(fields=['subscription', 'key'], name='saas_subscr_subscri_24ca14_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionattribute',
            index=models.Index(fields=['key'], name='saas_subscr_key_429186_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionattribute',
            unique_together={('subscription', 'key')},
        ),
    ]
