# Generated by Django 5.2.8 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyextension',
            options={},
        ),
        migrations.AddField(
            model_name='branch',
            name='is_all_branch',
            field=models.BooleanField(default=False, editable=False, help_text='System flag for the global all-encompassing Branch.'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='is_all_bu',
            field=models.BooleanField(default=False, editable=False, help_text='System flag for the global all-encompassing BU.'),
        ),
    ]
