# Generated by Django 5.2.8 on 2026-09-04 11:45

import core.base_models.audit_mixin
import core.base_models.permissions
import core.base_models.validator_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '__first__'),
        ('core_admin', '0003_alter_companyextension_options_branch_is_all_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Company base General Ledger reporting currency e.g. USD, SAR, EUR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_using_base', to='accounting.currency'),
        ),
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('version', models.IntegerField(default=1)),
                ('document_type', models.CharField(db_index=True, help_text="Logical type identifier, e.g. 'vendor', 'purchase_order'.", max_length=100)),
                ('pattern', models.CharField(help_text="Pattern for generated codes, e.g. 'VEN-{YYYY}{MM}-{SEQ:5}'. Supported tokens: {YYYY}, {YY}, {MM}, {DD}, {COMPANY_CODE}, {BU_CODE}, {BRANCH_CODE}, {SEQ}, {SEQ:n}.", max_length=255)),
                ('current_number', models.BigIntegerField(default=0, help_text='Last used sequence number for this series.')),
                ('number_length', models.PositiveIntegerField(default=5, help_text='Default zero-padding length for {SEQ} when no explicit length is given.')),
                ('reset_policy', models.CharField(choices=[('NEVER', 'Never'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='NEVER', help_text='When to reset the sequence counter.', max_length=16)),
                ('last_reset_at', models.DateTimeField(blank=True, help_text='Last time the sequence was reset (stored in UTC).', null=True)),
                ('prefix', models.CharField(blank=True, default='', help_text='Static string to prepend to the generated number.', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', help_text='Static string to append to the generated number.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this number series is currently active.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.businessunit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core_admin.company')),
            ],
            options={
                'verbose_name': 'Number Series',
                'verbose_name_plural': 'Number Series',
                'db_table': 'core_number_series',
                'abstract': False,
                'indexes': [models.Index(fields=['document_type'], name='core_number_documen_7b462e_idx'), models.Index(fields=['document_type', 'company'], name='core_number_documen_a39d88_idx'), models.Index(fields=['document_type', 'company', 'business_unit'], name='core_number_documen_9c4c78_idx'), models.Index(fields=['document_type', 'company', 'business_unit', 'branch'], name='core_number_documen_d7fecc_idx')],
            },
            bases=(core.base_models.validator_model.ValidatorModelMixin, core.base_models.validator_model.IdentityMixin, core.base_models.audit_mixin.AuditMixin, core.base_models.permissions.PermissionPolicyMixin, models.Model),
        ),
    ]
